SOURCES := ConcatRemove.cpp ConcatRemoveTest.cpp
CXX = g++
CPPFLAGS =        # put pre-processor settings (-I, -D, etc) here
CXXFLAGS = -Wall  # put compiler settings here
LDFLAGS =         # put linker settings here

test:
	$(CXX) $(SOURCES) -o $@ $(CXXFLAGS) $(LDFLAGS)

clean:
	rm -v test